name: Build Menu
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV
          echo "~/theos/bin" >> $GITHUB_PATH

     - name: Setup iOS SDK
        run: |
          mkdir -p ~/theos/sdks
          # استخدام رابط مباشر وموثوق للـ SDK
          curl -ksL https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz -o ~/theos/sdks/iPhoneOS14.5.sdk.tar.xz
          cd ~/theos/sdks
          tar -xf iPhoneOS14.5.sdk.tar.xz
          rm iPhoneOS14.5.sdk.tar.xz

      - name: Build Tweak
        run: |
          make package FINALPACKAGE=1
        env:
          THEOS: ~/theos

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mod-Menu-Dylib
          path: .theos/obj/debug/*.dylib
